@startuml
skinparam packageStyle rectangle

:admin:

:server:
admin --> (получить лог событий)
(получить лог событий) --> server

admin --> (отправить комментарий на сервер)
(отправить комментарий на сервер) --> server 

admin --> (добавить комментарий)
admin --> (просмотреть отмеченные события)


@enduml
